"""Add billing tables

Revision ID: 002_add_billing_tables
Revises: 001_initial
Create Date: 2026-04-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_billing_tables'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_plans',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('inr_per_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inr_per_1k_tokens', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inr_per_api_call', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('inr_per_session', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('flat_monthly_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pricing',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.String(length=255), nullable=True),
    sa.Column('credit_limit_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=True),
    sa.Column('custom_inr_per_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('custom_inr_per_1k_tokens', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('custom_inr_per_api_call', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('custom_inr_per_session', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('assigned_by', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('total_minutes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_api_calls', sa.BigInteger(), nullable=True),
    sa.Column('total_sessions', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_inr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('flat_fee_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grand_total_inr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'billing_month', name='uq_username_billing_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_summaries')
    op.drop_table('usage_events')
    op.drop_table('user_pricing')
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
