"""Update user model for RBAC and hierarchy

Revision ID: 003_update_user_hierarchy
Revises: 002_add_billing_tables
Create Date: 2026-04-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_update_user_hierarchy'
down_revision: Union[str, None] = '002_add_billing_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new RBAC-related columns to users table
    op.add_column('users', sa.Column('parent_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('permission_group', sa.String(length=255), default='global', nullable=False))
    op.add_column('users', sa.Column('permission_scope', sa.JSON(), default={}, nullable=False))
    op.add_column('users', sa.Column('created_by', sa.String(length=255), nullable=True))
    
    # Add foreign key constraint for parent_user_id (self-referential)
    op.create_foreign_key(
        'fk_users_parent_user_id',
        'users',
        'users',
        ['parent_user_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    # Migrate role values from old strings to new strings
    op.execute("UPDATE users SET role = 'admin' WHERE role = 'tenant_admin'")
    op.execute("UPDATE users SET role = 'reseller_admin' WHERE role = 'tenant_manager'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverse role migration
    op.execute("UPDATE users SET role = 'tenant_admin' WHERE role = 'admin'")
    op.execute("UPDATE users SET role = 'tenant_manager' WHERE role = 'reseller_admin'")
    
    # Drop foreign key constraint
    op.drop_constraint('fk_users_parent_user_id', 'users', type_='foreignkey')
    
    # Drop new columns
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'permission_scope')
    op.drop_column('users', 'permission_group')
    op.drop_column('users', 'parent_user_id')
